### ISSUE TITLE
[Feature suggestion] fill comments based on existing translation file

### ISSUE THREAD

**Issue by mrabus** [DanielNT/ALTranslationCenter#10]
Hi Daniel, 

I have a feature suggestion and honestly no idea if it's feasible to do it or not. 

I started using your extension recently and most of my older projects don't employ the Comment = "Language=Translation" syntax yet. Would it be possible to fill these comments based on an existing translation file? 

Would be happy to help and contribute, if possible

**Comment by DanielNT** [comment]
Hi @mrabus, thanks for the suggestion.

I suposse that making this will be difficult, because maybe needs to create a language server/using .NET and dll, so it will use extra resources and lose performance (more CPU usage), and needs more knowledge of VS Code development.

Moreover, the XLIFF source file could be not updated with last changes at the launching of the new command, so it may cause troubles in creating the syntax.

In any case, I will study it.

**Comment by DanielNT** [comment]
Using native symbols seems not a possibility, because it will only works with variables (as labels). Properties as _Caption_ cannot be found, so it will be impossible to map keeping it easy.
