### ISSUE TITLE
Occurrences in case of badly formatted caption, missing comma or first doublequote

### ISSUE THREAD

**Issue by DominicRoth** [DanielNT/ALTranslationCenter#2]
Hi Daniel,

finding most occurences in case of badly formatted caption works great! But if you forget an comma, it creates an file with a missing translation.

How the caption should be:
![image](https://user-images.githubusercontent.com/100766175/182380973-55137039-d847-4823-a1d2-86713f48dc53.png)

How it can be in this specific case:
![image](https://user-images.githubusercontent.com/100766175/182381621-6d42da34-d56c-4834-918b-5401a6a0aa29.png)

How the XLIFF would be:
![image](https://user-images.githubusercontent.com/100766175/182381937-76dbbd24-58d8-497e-8184-eb1bfc35585d.png)

As you can see, the XLIFF was created, but the target is missing.

Same behavior if the first doublequote of an translation is missing:
![image](https://user-images.githubusercontent.com/100766175/182384066-7d080b3e-9205-4c17-b057-8181f240dfec.png)

Greetings
Dominic

**Comment by DanielNT** [comment]
Hi Dominic, 

I suppose that the XLIFF with the missing target was at file _MyExtension.de-DE.xlf_, it didn't detect the language DEU because the missing comma, and all the text went to _MyExtension.de-AT.xlf_ (like the picture below).

![image](https://user-images.githubusercontent.com/12068767/182407030-3a08a347-3810-4eca-bbf9-4504db5cd254.png)

The problem is that it is difficult to say if there is an error in the comment writing (for example, in this case), or it is made on purpose, because the translation is just the string that you write.

This, for example, is clearly wrong and detected as error:
![image](https://user-images.githubusercontent.com/12068767/182410995-fac9aa2e-b33b-44e6-ba16-a4ca1a27b73d.png)

But in difficult cases, it may split a well-formed translation, if the label contains symbols like **=** or **"**.

I will investigate a bit if the error detection can be improved. Thanks.

**Comment by DanielNT** [comment]
@DominicRoth I've updated the extension at VS Code Marketplace to version 1.2.3. You can use a new option to set a Regex for comment, with the content like:

> **\D\D\D=(?:")** 

In your case, now throws an error. Needs to be tested carefully, false positives may occur.

**Comment by DominicRoth** [comment]
@DanielNT Thank you very much. A first testing seems very successfully! Directly found 6 badly formatted captions in my Extension! 👍
